In [1]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5]) 
print(arr)

[1 2 3 4 5]


In [3]:
 
import sys 

In [4]:
S= range(1000)
print("Size of each element of list in bytes: ", sys.getsizeof(S))

Size of each element of list in bytes:  48


In [5]:
print("Size of the whole list in bytes: " , sys.getsizeof(S)*len (S))

Size of the whole list in bytes:  48000


In [6]:
D= np.arange(1000)

In [7]:
print("Size of each element of the Numpy array in bytes: ",D.itemsize)

Size of each element of the Numpy array in bytes:  4


In [8]:
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize) 


Size of the whole Numpy array in bytes:  4000


In [9]:
arr = np.array(42) 
print(arr)

42


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) 
print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [12]:
zeros_arr = np.zeros((5,2)) 
eros_arr = np.zeros(5) 
print(zeros_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
zeros_arr = np.zeros((2,3)) 
print(zeros_arr) 

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
print("Data type of the array: ", zeros_arr.dtype)

Data type of the array:  float64


In [15]:
zeros_arr_int = np.zeros((3,3), dtype=np.int16) 
print("\nArray of zeros with integer elements: \n", zeros_arr_int)


Array of zeros with integer elements: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
ones_arr = np.ones(6) 
print(ones_arr) 

[1. 1. 1. 1. 1. 1.]


In [17]:
print("\nData type of the array: ", ones_arr.dtype)


Data type of the array:  float64


In [18]:
empty_arr = np.empty((3,2)) 
print(empty_arr) 


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
print("\nData type of the array: ", empty_arr.dtype)


Data type of the array:  float64


In [20]:
identity_matrix = np.eye (3) 
print(identity_matrix) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
identity_matrix = np. eye (4) 
print("\n", identity_matrix)


 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
arr1 = np.array([1, 2, 3], dtype=np. float64) 
arr2 = np.array([1, 2, 3], dtype=np.int32) 
print(arr1.dtype) 
print(arr2.dtype)

float64
int32


In [23]:
arr = np.array([1, 2, 3]) 
print("Before converting: ", arr, arr.dtype) 
new_arr = arr.astype('f') 
print("After converting: ", new_arr, new_arr.dtype) 


Before converting:  [1 2 3] int32
After converting:  [1. 2. 3.] float32


In [24]:
arr1 = np.arange(10) 
arr2 = np.random. randn (10) 
print("array 1\n", arr1, arr1.dtype) 
print("Array 2 \n", arr2, arr2.dtype) 
new_arr = arr1.astype (arr2.dtype) 
arr1.astype(arr2.dtype) 
print("New Array \n", new_arr, new_arr.dtype) 


array 1
 [0 1 2 3 4 5 6 7 8 9] int32
Array 2 
 [ 0.07827518 -0.13589065  0.14644493  0.90749449  1.29502343 -0.152261
 -0.17592324 -0.92168674 -0.61357431  0.87221864] float64
New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [25]:
str_arr = np.array(['hello', 'world', 'numpy']) 
print(str_arr) 
['hello' 'world' 'numpy'] 


['hello' 'world' 'numpy']


['helloworldnumpy']

In [28]:
import numpy as np 
a = np.array([1., 2., 3., 4.]) 
b = np.array([5., 6., 7., 8.]) 
print(a + b)  
print(a ** b) 

[ 6.  8. 10. 12.]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [30]:
import numpy as np 
arr = np.arange(12) 
newarr = arr.reshape(4, 3) 
print(newarr) 
newarr = arr.reshape((4, 3), order='F') 
print("\n", newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [31]:
import numpy as np 
arr = np.array([[1, 2, 3, 4,9,10], [5, 6, 7, 8,11,12]]) 
print(arr) 
newarr = arr. reshape (3, 2, 2) 
print("\n", newarr) 


[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]


In [35]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 1], [3, 5]])
greater_than = arr1 > arr2 
less_than = arr1 < arr2 
equal_to = arr1 == arr2 
print("Greater than: \n", greater_than)
print("\nLess than: \n", less_than)
print("\nEqual to: \n", equal_to) 


Greater than: 
 [[False  True]
 [False False]]

Less than: 
 [[ True False]
 [False  True]]

Equal to: 
 [[False False]
 [ True False]]


In [41]:

arr3 = np.array([1, 2, 3]) 
arr4 = np.array([1, 2, 3]) 
arr5 = np.array([1, 2, 4]) 
result2 = np.array_equal(arr3, arr5)
result1= np.array_equal(arr3, arr4) 
print("\nArray-wise comparison 1:", result1) 
print("Array-wise comparison 2:", result2)

x=  [0 1 2 3 4 5 6 7 8 9]

Array-wise comparison 1: True
Array-wise comparison 2: False


In [42]:
x = np.arange(10) 
print("x= ",x)
print("\n x[:5]= ",x[:5])
print("\n x[5:]= ",x[5:])
print("\n x[4:7]= ",x[4:7])
print("\n x[::2]= ",x[::2])
print("\n x[1::2]= ",x[1::2])
print("\n x[::-1]= ",x[::-1])
print("\n x[5::-2]= ",x[5::-2])

x=  [0 1 2 3 4 5 6 7 8 9]

 x[:5]=  [0 1 2 3 4]

 x[5:]=  [5 6 7 8 9]

 x[4:7]=  [4 5 6]

 x[::2]=  [0 2 4 6 8]

 x[1::2]=  [1 3 5 7 9]

 x[::-1]=  [9 8 7 6 5 4 3 2 1 0]

 x[5::-2]=  [5 3 1]


In [43]:
x = np.arange(10) 
print(x) 
x[5] = 2 
print("\n After broadcasting1",x) 

[0 1 2 3 4 5 6 7 8 9]

 After broadcasting1 [0 1 2 3 4 2 6 7 8 9]
